### ISSUE TITLE
Alternative location for raw data

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-2-devel#16]
Raw data are currently stored under the root folder of the dataset.
- The root folder gets cluttered by `sub-<label>` subfolders and hides important files such as `README` and derived data in `derivatives`.
- This also creates an imbalance with source data that are stored in `sourcedata` and derived data in `derivatives`.
Perhaps raw data could be stored in an (optional?) `rawdata` subfolder.

**Original authors**: Unknown

**Comment by jbteves** [comment]
The current folder hierarchy is inconsistent, as raw root should look identical to the `sourcedata` root in order to improve ease of comparison between the two and general symmetry.

**Comment by tsalo** [comment]
It's a little unclear to me what "raw data" refers to here, but I _assume_ it refers to the BIDS dataset. If it is the BIDS dataset, then I like the idea of enforcing a folder structure, when other top-level folders (e.g., `sourcedata`) are present.

**Comment by jbteves** [comment]
Ah, yes, I should have specified that I mean the originally converted niftis, rather than dicoms or preprocessed niftis when I gave this my thumbs-up.

**Comment by yarikoptic** [comment]
BIDS can be used for "study level" dataset ... concept is not really excercised, but someone can have

```
sourcedata/
   bids/
   dicoms/
derivatives/
  fmriprep-1/
dataset_description.json
README
```

I filed
- https://github.com/bids-standard/bids-specification/issues/1739
now which I think we can even address in BIDS 1.0

**Comment by yarikoptic** [comment]
as such I would vote to just close this issue in favor of that one back in bids-specification, WDYT @jbteves and @tsalo ?

**Comment by tsalo** [comment]
Sure!
