### ISSUE TITLE
Add a compulsory header to every JSON file

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-2-devel#35]
https://groups.google.com/forum/#!topic/bids-discussion/TjxOKEB1DD4 

add a 'header' block to _every_ JSON file that specifies the type of parameter file that it is and a spec version. This makes it a bit easier to verify that the file is what you think it is. This is particularly useful due to the very few mandatory keys in the files.

**Original authors**: @ccraddock

**Comment by jbteves** [comment]
Hey @tsalo if you're not part of the group you unfortunately can't see the discussion.

**Comment by tsalo** [comment]
I don't think that's a fixable issue, unfortunately. But the BIDS google group _should_ be open-join. I know it's not optimal to require people join a google group to access the original discussion, but it's best route available, I think.

**Comment by robertoostenveld** [comment]
> add a 'header' block to every JSON file that specifies the type of parameter file that it is 

How would this be different than using the information that is present in the JSON file name and especially the [suffix](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html), i.e. T1w or eeg, just before the extension.

> ... and a spec version

Would this open the possibility for having filees within one dataset complying to different versions of the specification?

**Comment by sappelhoff** [comment]
> Hey @tsalo if you're not part of the group you unfortunately can't see the discussion.

I just tried in a private browser (not logged in or anything) and I could see the discussion :thinking: the settings for the bids-discussion google group are "open", so I don't know what went wrong

Screenshots:

![image](https://user-images.githubusercontent.com/9084751/89389019-24c63800-d705-11ea-8aa8-08a3046eb7ae.png)

![image](https://user-images.githubusercontent.com/9084751/89389086-40314300-d705-11ea-98b1-0cc164c20444.png)

**Comment by jbteves** [comment]
Hm, today I don't get the same error. Weird. Thanks for checking on it.

**Comment by yarikoptic** [comment]
I think this issue is at large addressed by introducing the schema to BIDS. Although indeed every file could potentially point to the schema and its version, ATM we rely on BIDSVersion to be specified dataset wide and IMHO it is sufficient.  Since there were not much interest in this issue, and because I think it is principally addressed, I will just close. Please reopen if disagree
