### ISSUE TITLE
Formalize procedure of issues triage for BIDS 2.0 project

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-2-devel#56]
In principle all issues we have already filed should go through the
[BIDS 2.0](https://github.com/orgs/bids-standard/projects/10/views/1?layout=board) and be moved from "No status" to either "Punted" or "Todo" or even "In progress" or "Done" if somehow in those advanced stages.

There is a [listing of issues sorted by :+1: ](https://github.com/bids-standard/bids-2-devel/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) which could be of help to choose candidates

**Comment by tsalo** [comment]
I like that. I tried to classify the proposals based on their predicted level of impact, but we definitely need to label them based on status as well.

**Comment by yarikoptic** [comment]
Ok , for now it would be

**Decided by @yarikoptic with possible input from the community, based on difference between 👎 - 👍 or lack of enthusiasm/activity from others**.

Reopen if you would propose to refine and how
