### ISSUE TITLE
Add magnetization transfer

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-2-devel#6]
Also find a way to organize data for MT-related protocols (e.g. mt0+mt1 to compute MTR, mt0+mt1+t1w to compute MTsat, etc.). B1 mapping should also be accounted for in case researchers acquire it (but then, B1 map could be used for other purposes than MT protocol, so maybe not put it in the mt folder).

**Original authors**: @jcohenadad

**Comment by tsalo** [comment]
I believe that MT (both as an entity and as multiple suffixes) was rolled into BEP-001, so I'm going to label this as 1.0-compatible, but I'll hold off on closing it until BEP-001 has been merged.

**Comment by tsalo** [comment]
`mt` was added to the specification in https://github.com/bids-standard/bids-specification/pull/681, so I'm closing now.

**Comment by jcohenadad** [comment]
@tsalo this is awesome! thank you so much for this new feature. I can see the new MT-related fields were added to the [latest doc](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#sequence-specifics), however I am not sure how file should be named. Should it be something like this?
~~~
sub-01_acq-MTState1_PD.nii.gz
~~~

**Comment by tsalo** [comment]
@jcohenadad the key/value pairs for magnetization transfer are now `mt-on` or `mt-off`, and the entity goes between the new `inv` and `part` entities in filenames. In your case, I believe you'd want `sub-01_mt-on_PD.nii.gz` (for the file with the metadata field `MTState` set to True, I think) and `sub-01_mt-off_PD.nii.gz` (when `MTState` is False).

The `mt` entity has been accepted, so it will become officially supported in the next release (1.5.0), but currently it's not supported in `pybids`, `bids-matlab`, or `bids-validator`, although those are all on our to-do list.

One other thing worth noting is that BEP001 also deprecates the suffix `PD` in favor of `PDw` (for arbitrarily-scaled maps) and `PDmap` (for quantitative maps). The associated PR (https://github.com/bids-standard/bids-specification/pull/690) is not yet merged, but I think now's a good opportunity to adopt the new naming convention.

Hope that helps!

**Comment by jcohenadad** [comment]
> @jcohenadad the key/value pairs for magnetization transfer are now mt-on or mt-off, and the entity goes between the new inv and part entities in filenames. In your case, I believe you'd want sub-01_mt-on_PD.nii.gz (for the file with the metadata field MTState set to True, I think) and sub-01_mt-off_PD.nii.gz (when MTState is False).

Awesome! That does help. Thank you so much.

> One other thing worth noting is that BEP001 also deprecates the suffix PD in favor of PDw

Ah! I'm glad about this change. I always found it confusing to have T1"w" and T2"w" but not PD"w". Thanks!
